### ISSUE TITLE
u('#umbrella')

### ISSUE THREAD

**Issue by huei90** [umbrellajs/umbrella#12]
looking at the source code, instead of `#umbrella`, Umbrella is prefer using `document.getElementById('umbrella')` to get the `id` node

Any reason why doesn't support `#umbrella`?

**Comment by huei90** [comment]
Sorry, it does support.

**Comment by franciscop** [comment]
Hi @huei90, no problem. However, do you think comments in the source code could be improved so future visitors don't get confused?
