### ISSUE TITLE
u extends Array()

### ISSUE THREAD

**Issue by franciscop** [umbrellajs/umbrella#14]
> **[JSFiddle](https://jsfiddle.net/franciscop/v3ow0qwa/)**

Right now the nodes are stored in each of the instances of Umbrella like this:

```js
u('.demo').nodes   // the actual html elements are stored in this array
```

This gives some flexibility but it also has some pain points:

1. To know the **length** you'd need to do `u('.demo').nodes.length` instead of just `u('.demo').length`
1. There are many wrappers
1. "native" array function such as .map(), some(), etc must be manually implemented or used in `.nodes` such as `u(u('.demo').nodes.map(function(){ ... }));` which is really ugly

So there's a possible solution, this being that the base function, `u()`, extends the native Array. [This can be done](http://perfectionkills.com/how-ecmascript-5-still-does-not-allow-to-subclass-an-array/#naive_approach) in a [really easy way (jsfiddle)](https://jsfiddle.net/franciscop/v3ow0qwa/):

```js
var u = function(selector) {
	if (!(this instanceof u)) {
  	return new u(selector);
  }
  this.push.apply(this, document.querySelectorAll(selector));
}
u.prototype = Array.prototype;

u('a').forEach(n => console.log(n));
console.log(u('a'));
console.log(u('a').length);
```

With its own pain points:

- `length` should be treated as read-only or bad thins will happen
- there are few native functions that would collide with the functions now, like `slice`, `filter`, `find` and `join`, and each should be treated differently. While [they could be extended](http://jondavidjohn.com/extend-javascript-functions/) for the `u` object, it might be confusing. Note: no future compat problem since if a new method is added to ES2016 or whatever, it'd be override for `u()`.
- Those functions are not chainable

I think that at this point it makes no sense to do it, but maybe when I started umbrella I'd find it very useful

**Comment by leeoniya** [comment]
https://github.com/finom/bala does this

mentioned in https://github.com/umbrellajs/umbrella/issues/10

**Comment by franciscop** [comment]
I just commented there, unfortunately [it's difficult to see that...](https://github.com/finom/bala/blob/master/bala.js)

**Comment by leeoniya** [comment]
[but not terribly difficult :)](https://github.com/finom/bala/blob/master/bala.js#L3)

```js
$.fn = [];
bala = Object.create($.fn);
```

**Comment by franciscop** [comment]
Ohh I see, totally missed that from `$.fn = [];` down below :smile:

**Comment by leeoniya** [comment]
and i totally missed that *you* were the one who opened this issue :smile:

github's mobile UI is too gutted and using the desktop UI on a phone makes everything tiny.

**Comment by franciscop** [comment]
To solve **1.** this can be done:

```js
// Map u(...).length to u(...).nodes.length
Object.defineProperty(this, 'length', {
  __proto__: this.length,
  get: function(){
    return this.nodes.length;
  }
});
```

Inside the `var u = function(){}`. As it can be seen in [JSFiddle prototype](https://jsfiddle.net/franciscop/av8hg70j/), and [it's apparently ES5 feature](http://caniuse.com/#feat=es5) so no compatibility issues

**Comment by franciscop** [comment]
To solve **3.**, a method like this could be implemented. If the function returns an array, then put the new array in the place of the old array so you can keep chaining away. If it returns other kind of value, return it:

```js
// map()
u('a').array('map', function(node, i){ return node; });

// filter()
u('a').array('filter', function(node, i){ return node; });

// some()
var isThere = u('a').array('some', function(){ return i == 1 });

// ...
```

However this is actually quite strange (I think), so maybe it should be better documented that this is possible:

```js
var nodes = u('a').nodes.map(function(node){ return node; });
u(nodes);
```

Or perhaps just add the first proposed method dynamically for all of the array methods. However, here there's a collision problem (for example, filter):

```js
u('a').map(function(){  });
u('a').filter(function(){  });
var res = u('a').some(function(){  });
```

**Comment by franciscop** [comment]
The only unsolved part is **3.**, which I think should be left unchanged since adding a new function is really easy. Also, `filter()` is native-compatible, but it adds more flexibility specific to Umbrella JS (selector filter), so I like the way it is now. Closing this then
