### ISSUE TITLE
Implement .siblings(selector)

### ISSUE THREAD

**Issue by tr3intaydos** [umbrellajs/umbrella#16]
Something like this?

```js
u.prototype.siblings = function(selector) {
  
  var self = this;
  
  return this.join(function(node){
    return self.slice(node.parentNode.children);
  }).not(self).filter(selector);
};
```

**Comment by franciscop** [comment]
That looks great :+1: 

Do you want to help me do a roadmap? So we know what methods are more important and which should be prioritized (so we can avoid blocking functions as happened before)

**Comment by franciscop** [comment]
Would something like this work too? Sorry for not documenting `.parent()`:

```js
u.prototype.siblings = function(selector) {
  return this.parent().children(this).not(this);
};
```

**Comment by tr3intaydos** [comment]
Sure, a roadmap, should help a lot.

Yes, thats better, just add the .filter(selector)

**Comment by tr3intaydos** [comment]
Oooh i see, the children(). Sorry
