### ISSUE TITLE
HTML Generator

### ISSUE THREAD

**Issue by tr3intaydos** [umbrellajs/umbrella#20]
How do you feel about something like this:

```js
function parseHtml(htmlString){
  var d = document.createElement('div');
  d.innerHTML = htmlString;
  return u(d).children();
}
```

```js
var o = parseHtml('<p class="test">New <strong>paragraph</strong></p>');
u('body').append(o.first().outerHTML);
```

**Comment by franciscop** [comment]
I did the work for this part already, it was quite different:

```js
// Usage
u('<div>');

// Check in `.select()`
: /^</.test(parameter) ? this.select.html(parameter)
```

However, please read the [maybe] notes in [Roadmap and new features](https://github.com/umbrellajs/umbrella/issues/17#issuecomment-175228922) before continuing with this work, as I'm not yet sure whether or not they are within the scope of Umbrella

**Comment by tr3intaydos** [comment]
And u('<div class="test"></div>') ?

**Comment by franciscop** [comment]
However [that doesn't seem to be possible](http://stackoverflow.com/a/24470572/938236) using `insertAdjacentHTML`, which is used internally and that I don't think it's a good idea to change

**Comment by franciscop** [comment]
What do you mean with this?

```text
And u('
')
```

**Comment by tr3intaydos** [comment]
```js
u('<div class="test"></div>')
```

**Comment by franciscop** [comment]
Yes that also seems to be the same, since it only takes into account whether it starts by `<` or not (so it does). However without changing all the methods for inserting html, as you said, it doesn't make much sense to implement this and `.clone()`, and I don't think it's a good idea to change them. Sorry

**Comment by tr3intaydos** [comment]
I do think this is a required feature, its useful to, for example, generate html dynamically at an ajax callback

**Comment by tr3intaydos** [comment]
But your example maybe all it needs

**Comment by franciscop** [comment]
It is useful, but I think that the most useful part is what it's already there; an ajax call returning an html string can already be used since these methods would accept that string. While it'd be more useful if it could accept other things, I think that the cost for that (rewriting many parts of the core with sub-optimal methods) doesn't make it suitable.

**Comment by franciscop** [comment]
Yes, I just tested it. This stores them as nodes in the current `u()` object:

```js
var html = '<li><a href="#whatever">Bla</a></li><li><a href="#whatever">Bla</a></li>';
var lis = u(document.createElement('div')).html(html).children();
```

Then you can use `appendChild`, for example:

```js
lis.each(function(li){
  u('ul').first().appendChild(li);
});
```

**Comment by tr3intaydos** [comment]
I'm ok with that, closing.

**Comment by franciscop** [comment]
I opened it to implement what was suggested here. It should be implemented with some performance baked in though. See [StackOverflow](http://stackoverflow.com/a/3391622/938236) for an example.

**Comment by franciscop** [comment]
Okay, it was added. The `appendTo()` and any other ___To are not welcome, but otherwise it's compatible with jQuery. Actually it's much *better*, since all of these work:

```js
u('ul').append(el => `<li>${ el }</li>`, ['a', 'b', 'c']);
```

```js
function greeting(){ alert("Hello world"); }

u('ul').append(function(el) {
  return u('<li>').html(el).on('click', greeting);
}, ['a', 'b', 'c']);
```
