### ISSUE TITLE
.text(): create a function to get and set the text content

### ISSUE THREAD

**Issue by franciscop** [umbrellajs/umbrella#23]
Implement a method that returns the text of the first element or it sets it. Similar to `.html()`, but instead of returning `.innerHTML` it returns `textContent`. Then document and test the method. To do this:

- Clone the repository and install dependencies `npm install`
- Create the corresponding folder in `src/plugins`
- Execute `grunt watch` in the terminal. Make sure you also have [phantomjs](http://phantomjs.org/) installed first.
- Create the three files, `text.js`, `documentation.md` and `test.js`
- In `text.js` add the code needed to execute it
- Then (or before if you are into TDD) add the needed tests in `test.js`. After adding them all, open tests.html in your browser, which should show a passing/failing for your tests. Or check the terminal, since grunt should run tests now too.
- Add the `documentation.md` needed to use it
- Send a Pull Request and I'll provide feedback on the code

**Comment by tr3intaydos** [comment]
No `npm install` like in Contributing.md?

**Comment by franciscop** [comment]
Yes, sorry forgot to add that
