### ISSUE TITLE
.off(): create a function to detach events

### ISSUE THREAD

**Issue by franciscop** [umbrellajs/umbrella#24]
> This is an issue for newcomers and people who want to learn how to contribute to an open source project for the first time. Read more about this type of issues in [Up For Grabs](http://up-for-grabs.net)

Create a function opposite to `on()` capable of detaching a events from the matched elements. To do, please check [you might not need jquery](http://youmightnotneedjquery.com/#off) and follow these steps:

- Clone the repository
- Create the corresponding folder in `src/plugins`
- Execute `grunt watch` in the terminal. Make sure you have [phantomjs](http://phantomjs.org/) installed first.
- Create the three files, `off.js`, `documentation.md` and `test.js`
- In `off.js` add the code needed to execute it
- Then (or before if you are into TDD) add the needed tests in `test.js`. After adding them all, open tests.html in your browser, which should show a passing/failing for your tests. Or check the terminal, since grunt should run tests now too.
- Add the `documentation.md` needed to use it
- Send a Pull Request and I'll provide feedback on the code

Note: Check out `.on()` code to create `.off()`

I'll be happy to review any code you submit or add tips :smile:

**Comment by AHB** [comment]
Will give this a go in a bit

**Comment by franciscop** [comment]
Awesome, thank you

**Comment by franciscop** [comment]
Hey I added a small register for the events as `_e` in the nodes. This is not to require the second callback in the `.off()`, as jquery does. It's awesome that you added all the tests, since I could verify that it didn't break anything when changed it :smile:
