### ISSUE TITLE
.scroll(): go to the first matched element

### ISSUE THREAD

**Issue by franciscop** [umbrellajs/umbrella#30]
> This is an issue ready for newcomers and people who want to learn how to contribute to an open source project. Read more about this type of issues in [Up For Grabs](http://up-for-grabs.net)

Implement a method that moves the window to the first element. For this, [`scrollIntoView()` native method](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) is proposed as can be seen in #17. Steps:

- Clone the repository and install dependencies `npm install`
- Create the corresponding folder in `src/plugins`
- Execute `grunt watch` in the terminal. Make sure you also have [phantomjs](http://phantomjs.org/) installed first.
- Create the three files, `scroll.js`, `readme.md` and `test.js`
- In `scroll.js` add the code needed to execute it
- Then (or before if you are into TDD) add the needed tests in `test.js`. After adding them all, open tests.html in your browser, which should show a passing/failing for your tests. Or check the terminal, since grunt should run tests now too.
- Add the documentation to `readme.md` needed to use it
- Send a Pull Request and I'll provide feedback on the code

Example of use:

```js
u('a.team').on('click', function(e){
  e.preventDefault();
  u('section.team').scroll();
});
```

**Comment by CraigDMcKenna** [comment]
I'm interested but I'm new to umbrella.  Great website for this project by the way!

Do you have any plans to make this available on npm?

**Comment by franciscop** [comment]
I didn't think of publishing it with NPM, but of course it's an option since it's quite easy to do. Also thank you :+1: 

What would you need to get started? Are you stuck at some point, feeling it's a task too big to do or some other problem?

**Comment by CraigDMcKenna** [comment]
I'm not stuck (yet) I just wanted you to know that I'm on it this weekend. Thanks!

**Comment by franciscop** [comment]
Oh awesome, I misunderstood it. The tests might be challenging on Phantom JS though

**Comment by CraigDMcKenna** [comment]
Ok. Thanks for the heads up.

**Comment by CraigDMcKenna** [comment]
Ok. I'm getting into this now but I'm confused.

> For this, scrollIntoView() native method is proposed

So beyond the native functionality of scrollIntoView(), what should I be trying to accomplish here? Is it that you want the same functionality as scrollIntoView() on browsers that don't support this feature?

**Comment by franciscop** [comment]
I just saw that [you have contributed](https://github.com/CraigDMcKenna) to many other projects previously. I opened this mainly for the [up-for grabs](http://up-for-grabs.net/) project, however I forgot to add the disclaimer at the top of the issue:

> This is an issue ready for newcomers and people who want to learn how to contribute to an open source project. Read more about this type of issues in [Up For Grabs](http://up-for-grabs.net)

So yeah, it's really simple because it was intended for people who have never contributed before to open source, I apologize for not setting the disclaimer. The scope of the issue and the wanted PR is just adding the native functionality as an alias and then adding the appropriate tests and documentation. So if you are already started, please just wrap it up and do a PR :+1:

**Comment by CraigDMcKenna** [comment]
My bad. I haven't started though. All I have done is to clone the repo. Go ahead and let someone else take it.

**Comment by franciscop** [comment]
Oh no don't worry and do it if you want, I'll have to do both this and `size()` soon anyway so the branch `2` doesn't diverge too much from master. 

Also, if you want a real challenge you can check `.serialize()` issue for example (use the branch 2 in that case please).

**Comment by CraigDMcKenna** [comment]
Ok. Cool. Maybe I'll try both. I really haven't made any pull requests before just pushed up my own stuff and asked questions mostly.

**Comment by franciscop** [comment]
`scrollTo()` seems to be also native. The main point is not having to do it manually, so this:

```js
u('#contact').first().scrollIntoView({ behavior: smooth });
u('#contact').addClass('active');
```

Becomes simply this:

```js
u('#contact').scroll().addClass('active');
```

It is also thinking about the future; right now the smooth animation is only suported by Firefox, but in the future it will be better supported.

The main problems of doing the animation manually (like in `setInterval()` or `setTimeout()`) are:

- Performance: nothing is going to beat native methods
- Size: the amount of code required for it, including edge cases, is quite big.
- Scope: css-like animations are outside the scope or Umbrella JS. `.scroll()` is a one-off case (since it doesn't really fit anywhere) as an alias for convenience.
-Edge cases: like clicking an element while it's doing scroll from other, scrolling to an element while other is resizing, etc

**Comment by CraigDMcKenna** [comment]
I had issues with scrollIntoView in the past but I have been playing with it this morning.  Seems to work fine. (http://output.jsbin.com/sewomijuda/2)[http://output.jsbin.com/sewomijuda/2]

Maybe the issues I had were with certain display properties or something.

Sorry for over complicating this :grin:

**Comment by franciscop** [comment]
That looks great :+1:

**Comment by franciscop** [comment]
I made a small demo here, it works perfectly thanks for the code!:

> [JSFiddle](https://jsfiddle.net/franciscop/gwyg2735/)

**Comment by CraigDMcKenna** [comment]
:+1:
