### ISSUE TITLE
Don't remove attribute

### ISSUE THREAD

**Issue by franciscop** [umbrellajs/umbrella#31]
Right now this can be done and it will remove the attribute from the html:

```js
u('a').attr('href', null);
```

```html
<a href="#demo">Text</a>   =>   <a>Text</a>
```

While passing an empty string will just make it empty:

```js
u('a').attr('href', '');
```

```html
<a href="#demo">Text</a>   =>   <a href="">Text</a>
```

However, the behaviour is confusing at best, since the second parameter can be an *(empty) string*, *null* or *nothing (undefined)* and all of them will behave differently. So I will simplify it to only accept (string, string) or (object) for the setter and (string) for the getter. If you want to remove an attribute is really easy anyway:

```js
u('a').each(function(node){ node.removeAttribute('href'); });
```

**Comment by cjthompson** [comment]
You might want to add the suggestion on how to remove an attribute to the documentation for `attr`.  I was trying to simple hide/unhide an element by doing `u('#error').attr('hidden', 'hidden')` then `u('#error').attr('hidden', null)`.  Seems odd to be able to set `hidden` so easily not remove it.
