### ISSUE TITLE
Add .editorconfig

### ISSUE THREAD

**Issue by chriswburke** [umbrellajs/umbrella#33]
Add an .editorconfig to ensure contributors have the same code style.

**Comment by franciscop** [comment]
It doesn't seem to be [cross-editor out of the box](http://editorconfig.org/). Since we're using grunt, it would also make sense to hint/lint it. Would that work?

**Comment by chriswburke** [comment]
Yeah you have to install the plugin for most editors. JSHint/JSCS would make a lot of sense in this case.
