### ISSUE TITLE
Potentially errant comment in src/test.js

### ISSUE THREAD

**Issue by CraigDMcKenna** [umbrellajs/umbrella#38]
[This comment](https://github.com/umbrellajs/umbrella/blob/master/src/test.js#L7) seems out of place.

It's use seems correct [here](https://github.com/umbrellajs/umbrella/blob/master/src/test.js#L59) though.

**Comment by franciscop** [comment]
Yeah, my mistake. The whole test suite needs some rewritting. Like now we have size() that saves a lot of code and `if(work){}` should be added, but it's a lot of work. I'll see if I can get some done later today.

**Comment by franciscop** [comment]
It should be fixed now
