### ISSUE TITLE
.append() can only append last one from DOM

### ISSUE THREAD

**Issue by franciscop** [umbrellajs/umbrella#55]
When doing `.append()` with a node from the DOM tree, it removes it from the DOM and inserts it after the first element. Then removes it and inserts it after the second element. Then... inserts it on the last element. It is expected that it copies it into all of them, not just into the last one.

Example. We should see `{Content}` in all of them, however we only see it in the last one:

> [**JSFiddle**](https://jsfiddle.net/franciscop/9bh0md69/)

```html
{<span></span>} <br>
{<span></span>} <br>
{<span></span>} <br>
{<span></span>} <br>
{<span></span>} <br>
{<span></span>} <br>

<a>Content</a>
```

```js
u("span").append(u('a'));
```

**Comment by franciscop** [comment]
It's not technically a bug because that behaviour (passing u() to `.append()`) is not documented. However, it's a bug to the *expected* behaviour.

**Comment by ianwhitedeveloper** [comment]
@franciscop fyi I'm currently working on this bug. Think I may have figured it out. I'll get back to you with some details shortly.

**Comment by franciscop** [comment]
It looks perfect, I wasn't sure about departing the default *no clone* by default from jQuery but I think it's the best way since Umbrella's `.append()` is a bit different.
