### ISSUE TITLE
.replace() an element for a new one

### ISSUE THREAD

**Issue by franciscop** [umbrellajs/umbrella#56]
Implement a method that replaces the matched elements with the passed argument. So far the argument gets processed with the constructor `u()` and it accepts an html tag like `<div>` or a function that returns it. Steps:

- Clone the repository and install dependencies `npm install`
- Create the corresponding folder in `src/plugins`
- Execute `grunt watch` in the terminal. Make sure you also have [phantomjs](http://phantomjs.org/) 1.9.8 installed first.
- Create the three files, `replace.js`, `readme.md` and `test.js`
- In `replace.js` add the code needed to execute it
- Then (or before if you are into TDD) add the needed tests in `test.js`. After adding them all, open tests.html in your browser, which should show a passing/failing for your tests. Or check the terminal, since grunt should run tests now too.
- Add the documentation to `readme.md` needed to use it
- Send a Pull Request and I'll provide feedback on the code

Example of use:

```js
// Change the save button for an update one
u('.save').replace('<button class="update">Update<button>');

// Change the element button with a link with the class button
u('button').replace(function(btn){
  return '<a class="button">' + btn.innerHTML + '</a>';
});
```

> Note: probably #55 will affect this. But ignore that specific case and when #55 is fixed this will be fixed.

**Comment by paxmugisha** [comment]
Hi @franciscop I am interested in working on this issue. I'll clone the repo and work on it

**Comment by franciscop** [comment]
Awesome, thank you. If you have any question or problem just ask :)

**Comment by paxmugisha** [comment]
Great :) I have a question on the function case.
Is the argument of the function  the matched element? In your example u('button')

// Change the element button with a link with the class button
u('button').replace(function(btn){
  return '<a class="button">' + btn.innerHTML + '</a>';
});

**Comment by franciscop** [comment]
Yes sure, in that example it would convert this:

```html
<button>One</button>
<button>Two</button>
```

Into this:

```html
<a class="button">One</button>
<a class="button">Two</button>
```

So the callback should be called once for each of the matched elements (tip: check how the code of `.parent()` uses the function `.join()`).

**Comment by franciscop** [comment]
Hey @paxmugisha, I ended up changing quite a few things to be able to return the new elements in the Umbrella instance. There was [some issue with Phantom JS](https://github.com/ariya/phantomjs/issues/11958#issuecomment-217647882) so the return method couldn't be properly tested.

The core reuses the same `node.parentNode.replaceChild`, but by using `.adjacent` now we have a lot more of flexibility. I also fixed a couple of tests that were not properly closing the `</button>`

**Comment by paxmugisha** [comment]
Hi @franciscop thanks I follow the project now and I'll be happy to contribute :)

**Comment by paxmugisha** [comment]
Hi @franciscop I just realized the example in documentation http://umbrellajs.com/documentation#replace  ```js u('.save').replace('<button class="update">Update<button>');``` doesn't contain a close </button> tag neither. Should I open an issue to correct this?

**Comment by franciscop** [comment]
Oh I'll just reopen this to remember, but it's just a typo and not worth of a full issue in my opinion.

**Comment by franciscop** [comment]
Fixed
