### ISSUE TITLE
Create .clone() method

### ISSUE THREAD

**Issue by franciscop** [umbrellajs/umbrella#64]
This is not trivial since the events are not cloned by default, so there has to be some magic.

[Here is the problem](https://github.com/umbrellajs/umbrella/pull/62#issuecomment-217666427) as found by @ianwhitedeveloper :

- Get all of the elements. The current one and all of its children. Similar to [jquery's getAll](https://github.com/jquery/jquery/blob/305f193aa57014dc7d8fa0739a3fefd47166cd44/src/manipulation/getAll.js)
- Use the possible property called `._e` in the html elements (*nodes*) for reassigning the events to all the children. Check that when cloned with `.cloneNode(true)` this is also copied

Notes:

- Copy the events this by default. I don't think it's good idea to give options, as the nodes can be postprocessed later on.
- Add tests for form elements to see if their status and input is cloned or not. It *should* be cloned by default.

PS, @ianwhitedeveloper I made you Umbrella JS collaborator, so please feel free to push straight to master but leave me the version releases if possible (don't update the version numbers).

**Comment by franciscop** [comment]
It seems it keeps the `<input>` value: https://jsfiddle.net/042mea6x/3/

Also the *checkbox* value: https://jsfiddle.net/042mea6x/2/

And the *radio* value: https://jsfiddle.net/042mea6x/4/

But **not** the *select* one: https://jsfiddle.net/042mea6x/6/

**Nor** the *textarea* one: https://jsfiddle.net/042mea6x/7/

See this: [
Why don't select and textarea value changes get updated upon cloning as with input elements?
](http://stackoverflow.com/q/21059496/938236)

**Comment by ianwhitedeveloper** [comment]
Getting started on this today.

**Comment by franciscop** [comment]
@ianwhitedeveloper [this](http://stackoverflow.com/a/21060052/938236) and [this](http://stackoverflow.com/a/743871/938236) might be useful.

**Comment by franciscop** [comment]
@ianwhitedeveloper any update?

**Comment by ianwhitedeveloper** [comment]
@franciscop so sorry I've been rather swamped lately. I'm hoping to continue work on this feature this week/weekend.

**Comment by franciscop** [comment]
no problem, just checking in 👍

**Comment by ianwhitedeveloper** [comment]
@franciscop made some progression tonight. got cloning single and nested nodes w/events tests to pass. Need many more tests + code needs a lot of cleaning up and probably will make some other helper methods ala jQuery. Pretty tired atm but will try to make some more progress tomorrow or the next day.
:)

progress so far:
https://github.com/ianwhitedeveloper/umbrella/tree/create-clone-method

**Comment by franciscop** [comment]
The code is looking great. I think the `getAll()` could be simplified as a simple `u("*", node)`, however it seems like it doesn't get also the current node (only children) in the original.

When checking jQuery, take into account that many of the code is for old browser compatibility or for speed optimization. However, most browsers have changed their JS engines and some of these speed optimizations doesn't make sense anymore. See https://github.com/jquery/learn.jquery.com/issues/697 for just an example on tutorials. So don't worry about making things super simple.

**Comment by franciscop** [comment]
I am not sure what the data part is doing in jquery, I need to dig in. About the form elements values, I'd say if it's easy let's do it. I we need to build a whole form engine just to process that then let's ignore it and keep it like jquery.

**Comment by franciscop** [comment]
Here is a good explanation of what jQuery is doing with the data attributes:

[what is the meaning of jquery random attributes in html ? [expando attribute]](http://stackoverflow.com/questions/3922441/what-is-the-meaning-of-jquery-random-attributes-in-html-expando-attribute)

Basically all of the `data-` attributes are cached so it needs it to keep it up. Umbrella does nothing like that, so no need to do anything with the data attributes (they are being copied by default). Maybe add a test to make sure everything's good. See it [in jQuery's data()](https://github.com/jquery/jquery/blob/master/src/data.js#L45).

**Comment by franciscop** [comment]
Do you think we could or should use an object to allow for making it extensible? I am [reading how cloning values is too expensive](http://stackoverflow.com/questions/742810/clone-isnt-cloning-select-values) so it might make sense. Something like this:

```js
u.prototype.clone = function(){
  // your code

  for (i = 0, l = srcElements.length; i < l; i++) {
    for (var key in this.mirror) {
      this.mirror[key](srcElements[ i ], destElements[ i ]);
    }
  }
};

u.prototype.mirror = {};

u.prototype.mirror.events = function(source, destination){
  // your code for "cloneCopyEvent"
}
```

Then someone who wants to clone also the select with values can just add this in their code:

```js
u.prototype.mirror.select = function(src, dest){
  if (src.nodeName === "SELECT") {
    dest.value = src.value;
  }
}
```

This is similar to how [u.prototype.select](https://github.com/umbrellajs/umbrella/blob/master/src/plugins/select/select.js) is implemented now. For example, it can be extended as:

```js
// Select by data-id over a number
u.prototype.selectors[/^\+[\w\-]+$/] = function (param) {
  return u("[data-id]").filter(function(node){
    return parseInt(u(node).data('id')) > param.substring(1);
  }).nodes;
};

u('+25').addClass("older");
```

**Comment by ianwhitedeveloper** [comment]
@franciscop I like the idea of making the method extensible and I will try to incorporate that functionality.  BTW I noticed you changed .join to .map and it caused some confusion for me when I started back up on the project. Would it be good idea to make .join an alias for .map in case it could help others avoid confusion?

**Comment by ianwhitedeveloper** [comment]
@franciscop FYI using the demos you provided I noticed that in chrome canary 53 and chrome 51 using cloneNode does copy the textarea input values to cloned nodes. This isn't the case in the latest Firefox.
https://jsfiddle.net/042mea6x/7/  (change .join to .map an run to fix js error)

**Comment by franciscop** [comment]
A small demo to test the functionality. Apparently, contrary to what it says everywhere, jQuery has integrated it:

> https://jsfiddle.net/franciscop/h77tcrsd/
