### ISSUE TITLE
Namespace events in .on() and .off()

### ISSUE THREAD

**Issue by kylehalleman** [umbrellajs/umbrella#70]
I think it would be beneficial to be able to namespace events like in jQuery, where you can go `u('button').on('click.namespace')` so you can easily turn off just that namespaces event and not all click handlers on the button. I find this useful when I'm triggering custom events on the document in an Ajaxy site. Otherwise events start multiplying.

**Comment by franciscop** [comment]
I think the benefit is too small for the cost it carries to implement it (both in size and complexity). Umbrella JS isn't intended to be a clone of jQuery, just keeping compatibility where it makes sense and departing from it where it doesn't and I think it's better if we keep this outside of Umbrella's scope.

I didn't totally undestand "*I find this useful when I'm triggering custom events on the document in an Ajaxy site*". If you are trying to define custom event names and trigger them manually, [you are able to do so](https://jsfiddle.net/franciscop/cdkunkxx/).

**Comment by kylehalleman** [comment]
I understand not wanting to implement it. If everything gets added eventually it'd turn into jQuery.

I didn't explain what I'm doing well. i am using custom events but thought I needed namespaces to do some stuff but as I started explaining it here I think I found out how to do what I want with namespacing.

Appreciate the quick feedback. Keep up the good work.

**Comment by franciscop** [comment]
Can I ask what you ended up doing? While not adding namespaces, maybe we could add a note to the documentation for anyone looking for namespaces.
