### ISSUE TITLE
Touch enabled slider through umbrella

### ISSUE THREAD

**Issue by Swizz** [umbrellajs/umbrella#72]
Hi there !

Did anyone already made a touch enabled caroussel through umbrella ?

I am looking about to make the tiniest web app.
Umbrella is a great challenger :)

Cheers,

**Comment by franciscop** [comment]
No as far as I know. Umbrella JS is like jQuery, it's the base to build your components. See this question on StackOverflow:

> [How to recognize touch events using jQuery in Safari for iPad?
](http://stackoverflow.com/a/4755579/938236)

And the answer:

> Core jQuery doesn't have anything special for touch events, but you can easily build your own using the following events:
>
> - touchstart
> - touchmove
> - touchend
> - touchcancel
>
> For example, the touchmove
>
> ```
> document.addEventListener('touchmove', function(e) {
>    e.preventDefault();
>    var touch = e.touches[0];
>    alert(touch.pageX + " - " + touch.pageY);
> }, false);
> ```
