### ISSUE TITLE
.handle() cannot delegate

### ISSUE THREAD

**Issue by franciscop** [umbrellajs/umbrella#76]
`.handle()` is similar to `.on()` but preventingDefault, however it cannot delegate right now because it expects the second parameter to be the function:

```
TypeError: b.apply is not a function
```

**Comment by khannavidur** [comment]
Hello, I am new to open source ... can I pick this up?
Would require some guidance though. Thanks

**Comment by franciscop** [comment]
Sure no problem, it should be easy to implement it, however I haven't had time to do so. Any question please ask. The main problem(s) you might find are with the installation of the environment.

**Comment by franciscop** [comment]
Sure no problem, it should be easy to implement it, however I haven't had time to do so. Any question please ask. The main problem(s) you might find are with the installation of the environment.

**Comment by ianwhitedeveloper** [comment]
Hey @franciscop been a while! I think I'll tackle this one this weekend. Might reach out to you for an example or two if I can't figure out what's going on after looking at the problem a bit closer.

**Comment by franciscop** [comment]
Hey @ianwhitedeveloper perfect, thanks. It seems like @khannavidur didn't continue it. It shouldn't be too difficult I think, anything just ask me (:

**Comment by franciscop** [comment]
Any update, @ianwhitedeveloper ? :smile:

**Comment by franciscop** [comment]
I went ahead and fixed it since I am using a workaround on some code I'm shipping (so I can stop doing the workaround)

**Comment by ianwhitedeveloper** [comment]
sorry buddy got busier that I thought I'd be this past weekend :/

**Comment by franciscop** [comment]
No problem, I've been super busy last month but needed to ship this so I just pushed it (;
