### ISSUE TITLE
One-time Events

### ISSUE THREAD

**Issue by NetLancer** [umbrellajs/umbrella#80]
(as a request for new feature) Just one-time event handling like JQuery has:
https://www.sitepoint.com/create-one-time-events-javascript/  -would be great!

**Comment by franciscop** [comment]
That's really nice but I think it's better to keep it out of the core. It could be easily constructed as this (untested):

```js
u.prototype.once = function(events, cb){
  return this.eacharg(events, function(node, event){
    node.addEventListener(event, function(e){
      e.target.removeEventListener(event, arguments.callee);
      return callback.apply(this, arguments);
    });
  });
}
```

So then you can call it and use it:

```js
u('.cta').once('click', function(e){
  // whatever
});
```

> Note this way it doesn't accept a *live* version as in `.once('click', '.button', fn())` nor `.off('click')` for simplicity sake, check out `on()` if you want/need those.
