### ISSUE TITLE
New patch release?

### ISSUE THREAD

**Issue by jerodsanto** [umbrellajs/umbrella#81]
Howdy, I'm loving Umbrella! In fact, we're using it heavily on the next version of [changelog.com](https://changelog.com) (launch imminent)! 🍻 

There's an annoying little `console.log` when performing ajax requests that you [recently purged](aa368870755afccaf18e50b1199fd766847211b6), but it's still in the current release (2.6.6). Any chance I can talk you in to cutting a new one for us? 💚

**Comment by franciscop** [comment]
[Here you go](https://github.com/umbrellajs/umbrella/releases/tag/2.6.7), sorry for taking so long I had some dependencies installation trouble. Thanks for using Umbrella! If something doesn't work as expected please report it (:

**Comment by jerodsanto** [comment]
@franciscop thanks! 🎉
