### ISSUE TITLE
How to get help (for dummies :)?

### ISSUE THREAD

**Issue by NetLancer** [umbrellajs/umbrella#82]
Problem is I can't cope with getting array items to check if (click)event.target is ANY of those. 
Details:  'My Contacts' block (all inside UL > LI) each (LI) item reveals on hover. But I need js to add some flavour for touchscreens, that is click or tap on block, yet outside of span text & outside of icons reveals all items (by adding class) for a while. 
https://jsfiddle.net/jetcompass/j5z9Lkjb/#&togetherjs=CoguwRQ72v
Would be much thankful for any help

**Comment by franciscop** [comment]
I am not sure if this helps, but you are trying to use `some()` against `u()`; `u()` doesn't return an array, it returns an Umbrella object. The array itself is in `u().nodes`, so you could do:

```js
txtnodes.nodes.some(...)
```

However, I recommend using event delegation for this situation. It works in a similar way (hopefully same) to jQuery:

```js
function hreveal(evt) {
  evt.currentTarget  // Should be <span>
  evt.target // Should be <span> or a child of it
};
u('#reveal_contacts').on('click', 'div.link_title span', hreveal);
```

[JSFiddle](https://jsfiddle.net/franciscop/j5z9Lkjb/9/)

**Comment by NetLancer** [comment]
Thanx franciscop, the point is it shouldn't be one of spans (anything outside of spans yet within #reveal_contacts), but it seems I've got easier one:
`function hreveal(evt) {
		if (evt.target === evt.currentTarget) { // which is UL tag
			rcitems.toggleClass("width100pc");
			setTimeout(function(){
				rcitems.toggleClass("width100pc");
			}, 3000);
    }
  };`
http://uzlander.site50.net/
Nice small library, essential for devs (at least those of my level :))
