### ISSUE TITLE
Get by index

### ISSUE THREAD

**Issue by tleb** [umbrellajs/umbrella#83]
I am new to umbrella and I can't find the way to do an elementary thing: get a child by index. Brackets don't work. I could use `filter()` but it loops on every el:

```javascript
u("#parent").children().filter(function(node, i) { return i == index; })
```

Did I miss a `get()` function in the doc or something?

Great lib, thanks!

**Comment by franciscop** [comment]
Sure, you could use `.nodes` which holds the actual array with the elements:

```js
let el = u("#parent").children().nodes[index];
```

Or [use `find()` array method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) to the nodes array if you have a more complex query:

```js
let el = u("#parent").children().nodes.find((node, i) => i === index && ...);
```

**Comment by tleb** [comment]
Great, thanks!
